---
- name: Update package manager
  become: true
  ansible.builtin.package:
    update_cache: true
  tags:
    - pkg

- name: Install softwares with package manager
  become: true
  ansible.builtin.package:
    name:
      "{{ dkr_packages }}"
  register: result
  when: ansible_pkg_mgr != "pacman"
  ignore_errors: true
  tags:
    - pkg

- name: Print variables
  ansible.builtin.debug:
    var: result

- name: Create docker network
  community.docker.docker_network:
    name: "{{ dkr_network }}"
    driver: bridge
    state: present
  register: result
  when: use_dkr_net

- name: Add user to docker group
  ansible.builtin.user:
    name: '{{ adm_user }}'
    groups: docker
    append: true
  register: result

- name: Print variables
  ansible.builtin.debug:
    var: result

- name: Chmod /var/run/docker
  become: true
  ansible.builtin.file:
    path: "{{ var_run_dkr }}"
    state: file
    owner: root
    group: root
    mode: '0666'
  ignore_errors: true
  register: result
  changed_when: result.rc == 0

- name: Print variables
  ansible.builtin.debug:
    var: result
