---
- name: Update package manager
  become: true
  ansible.builtin.package:
    update_cache: true
  tags:
    - pkg

- name: Install softwares with package manager
  become: true
  ansible.builtin.package:
    name: "{{ dkr_packages }}"
  register: pkg_install_result
  when: ansible_pkg_mgr != "pacman"
  ignore_errors: true
  tags:
    - pkg

- name: Print package installation result
  ansible.builtin.debug:
    var: pkg_install_result
  when: pkg_install_result is defined

- name: Create docker network
  community.docker.docker_network:
    name: "{{ dkr_network }}"
    driver: bridge
    state: present
  register: docker_network_result
  when: use_dkr_net | default(true)

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ adm_user }}"
    groups: docker
    append: true
  register: user_group_result

- name: Print user group modification result
  ansible.builtin.debug:
    var: user_group_result

- name: Chmod /var/run/docker
  become: true
  ansible.builtin.file:
    path: "{{ var_run_dkr }}"
    state: directory
    owner: root
    group: docker
    mode: '0775'
  ignore_errors: true
  register: chmod_result
  changed_when: chmod_result.changed

- name: Print chmod result
  ansible.builtin.debug:
    var: chmod_result
